version: '3.8'

services:
  nginx-webui:
    image: registry.cn-shanghai.aliyuncs.com/numen/nginx-webui
    ports:
      - "8001:8001"
    volumes:
      - ./nginx:/app/nginx
      - ./data:/app/data
    environment:
      - APP_PORT=8001
      - NGINX_DIR=/app/nginx
    restart: unless-stopped

