version: '3.8'

services:
  nginx-webui:
    image: registry.cn-shanghai.aliyuncs.com/numen/nginx-webui
    ports:
      - "800:8000"
      - "443:443"
      - "80:80"
    volumes:
      - /opt/nginx-webui/data:/app/data
      - /opt/nginx-webui/letsencrypt:/etc/letsencrypt
    environment:
      - APP_PORT=8000
    restart: always
