nginx:
  config_path: ../nginx/nginx.conf
  executable: /usr/sbin/nginx
  static_dir: ../data/html
  log_dir: ../data/logs
  conf_dir: ../nginx/conf.d
  access_log: ../data/logs/access.log
  error_log: ../data/logs/error.log
  ssl_dir: ../data/ssl
  certbot_path: /usr/bin/certbot
  versions_root: ../nginx/versions
  build_root: ../nginx/build
  build_logs_dir: ../nginx/build_logs

app:
  host: 127.0.0.1
  port: 8000
  secret_key: # 从环境变量读取
  debug: true  # 调试模式，启用代码更改自动重载

backup:
  max_backups: 10
  backup_dir: ./data/backups

