export {
  ArrowDown,
  ArrowLeftRight as Switch,
  ArrowUp,
  BadgeCheck as Finished,
  Check,
  CircleCheckBig as CircleCheck,
  CirclePause as VideoPause,
  CirclePlay as VideoPlay,
  CirclePlus,
  Copy as CopyDocument,
  Cpu,
  Download,
  Eye as View,
  FileCheck2 as DocumentChecked,
  FilePlus2 as DocumentAdd,
  FileText as Document,
  Folder,
  FolderOpen as FolderOpened,
  FolderPlus as FolderAdd,
  Gauge as Odometer,
  House as HomeFilled,
  Info as InfoFilled,
  KeyRound as Key,
  Link,
  ListChecks as Select,
  LockKeyhole as Lock,
  LogOut as SwitchButton,
  Network as Connection,
  Package as Box,
  PanelLeftClose as Fold,
  PanelLeftOpen as Expand,
  PenLine as EditPen,
  Pencil as Edit,
  Plus,
  RefreshCw as Refresh,
  RefreshCw as RefreshRight,
  Rocket as Promotion,
  Scissors as Scissor,
  Search,
  Settings as Setting,
  Share2 as Share,
  SlidersHorizontal as Operation,
  Trash2 as Delete,
  Undo2 as RefreshLeft,
  Upload,
  UploadCloud as UploadFilled,
  User,
  WandSparkles as MagicStick,
  Wrench as Tools,
  X as CloseBold,
  Zap as Lightning,
  ChevronRight as ArrowRightBold,
  ChevronUp as ArrowUpBold,
} from 'lucide-vue-next'
