## 在非 root 权限下运行时，禁用 user 指令以避免无意义的告警
#user www-data;
worker_processes auto;
## 将 pid 文件放到 Nginx 前缀下的 logs 目录（配合 -p <install_path>，每个版本各自维护 pid）
pid logs/nginx.pid;

## 如果你本机没有 /etc/nginx/modules-enabled，可以先注释掉这行
#include /etc/nginx/modules-enabled/*.conf;

events {
    worker_connections 768;
}

http {
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;

    ## 使用项目内自带的 mime.types，而不是系统路径
    include /Users/wesley/wokerspacs/nginx-webui/nginx/versions/1.28.0/conf/mime.types;
    default_type application/octet-stream;

    ## 将日志输出到项目的 data/logs 目录
    access_log /Users/wesley/wokerspacs/nginx-webui/data/logs/access.log;
    error_log  /Users/wesley/wokerspacs/nginx-webui/data/logs/error.log;

    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types text/plain text/css text/xml text/javascript application/json application/javascript application/xml+rss;

    ## 引用当前项目下的 conf.d 配置
    include /Users/wesley/wokerspacs/nginx-webui/nginx/conf.d/*.conf;
    ## 如果你有额外站点配置，可在上面这行基础上新增 include
}

